name: Release workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Configure git
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub Action"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Prepare and perform release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO:
      run: |
        mvn --batch-mode -s .github/settings.xml release:prepare release:perform -DpushChanges=false -DlocalCheckout=true
        git push --follow-tags
